// This file is generated by Slice Machine. Update with care!

import MapasReactUsandoLeaflet from './MapasReactUsandoLeaflet';

export {
	MapasReactUsandoLeaflet,
};

export const components = {
	mapas_react_usando_leaflet: MapasReactUsandoLeaflet,
};
